name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install pyyaml
          pip install webdrivermanager
          webdrivermanager chrome

      - name: Run Robot Framework tests
        run: |
          cd AutoFinalExamDojo
          robot --variable Browser:chrome --outputdir results tests/

      - name: Upload Robot results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: AutoFinalExamDojo/results
